//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IVUServiceIntervals
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ivu.de/mb/intf/vehicle/remote", ConfigurationName="IVUServiceIntervals.VehicleWebFacade")]
    public interface VehicleWebFacade
    {
        
        // CODEGEN: Generating message contract since the operation importVehicles is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ivu.de/mb/intf/vehicle/remote", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CostCenter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vehicle))]
        IVUServiceIntervals.importVehiclesResponse importVehicles(IVUServiceIntervals.importVehicles request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ivu.de/mb/intf/vehicle/remote", ReplyAction="*")]
        System.Threading.Tasks.Task<IVUServiceIntervals.importVehiclesResponse> importVehiclesAsync(IVUServiceIntervals.importVehicles request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/vehicle/remote")]
    public partial class VehicleRequest
    {
        
        private string requestTypeField;
        
        private VehicleWithCostCenterRequest[] vehicleField;
        
        private VehicleGroup[] vehicleGroupField;
        
        private int protocolTransactionIdField;
        
        private bool protocolTransactionIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string requestType
        {
            get
            {
                return this.requestTypeField;
            }
            set
            {
                this.requestTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("vehicle", IsNullable=true, Order=1)]
        public VehicleWithCostCenterRequest[] vehicle
        {
            get
            {
                return this.vehicleField;
            }
            set
            {
                this.vehicleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("vehicleGroup", IsNullable=true, Order=2)]
        public VehicleGroup[] vehicleGroup
        {
            get
            {
                return this.vehicleGroupField;
            }
            set
            {
                this.vehicleGroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int protocolTransactionId
        {
            get
            {
                return this.protocolTransactionIdField;
            }
            set
            {
                this.protocolTransactionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool protocolTransactionIdSpecified
        {
            get
            {
                return this.protocolTransactionIdFieldSpecified;
            }
            set
            {
                this.protocolTransactionIdFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/vehicle/remote")]
    public partial class VehicleWithCostCenterRequest : Vehicle
    {
        
        private CostCenterRequest costCenterRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CostCenterRequest costCenterRequest
        {
            get
            {
                return this.costCenterRequestField;
            }
            set
            {
                this.costCenterRequestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/vehicle/remote")]
    public partial class CostCenterRequest : CostCenter
    {
        
        private string requestTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string requestType
        {
            get
            {
                return this.requestTypeField;
            }
            set
            {
                this.requestTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CostCenterRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/vehicle/remote")]
    public partial class CostCenter
    {
        
        private string abbreviationField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string abbreviation
        {
            get
            {
                return this.abbreviationField;
            }
            set
            {
                this.abbreviationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/vehicle/remote")]
    public partial class VehicleResponse
    {
        
        private VehicleKeyResponse[] vehicleKeyResponsesField;
        
        private VehicleGroupKeyResponse[] vehicleGroupKeyResponsesField;
        
        private int protocolTransactionIdField;
        
        private bool protocolTransactionIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("vehicleKeyResponses", IsNullable=true, Order=0)]
        public VehicleKeyResponse[] vehicleKeyResponses
        {
            get
            {
                return this.vehicleKeyResponsesField;
            }
            set
            {
                this.vehicleKeyResponsesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("vehicleGroupKeyResponses", IsNullable=true, Order=1)]
        public VehicleGroupKeyResponse[] vehicleGroupKeyResponses
        {
            get
            {
                return this.vehicleGroupKeyResponsesField;
            }
            set
            {
                this.vehicleGroupKeyResponsesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int protocolTransactionId
        {
            get
            {
                return this.protocolTransactionIdField;
            }
            set
            {
                this.protocolTransactionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool protocolTransactionIdSpecified
        {
            get
            {
                return this.protocolTransactionIdFieldSpecified;
            }
            set
            {
                this.protocolTransactionIdFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/vehicle/remote")]
    public partial class VehicleKeyResponse : VehicleKey
    {
        
        private ProtocolEntry[] protocolEntryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("protocolEntry", IsNullable=true, Order=0)]
        public ProtocolEntry[] protocolEntry
        {
            get
            {
                return this.protocolEntryField;
            }
            set
            {
                this.protocolEntryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/vehicle/remote")]
    public partial class ProtocolEntry
    {
        
        private string typeField;
        
        private int codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(VehicleKeyResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/vehicle/remote")]
    public partial class VehicleKey
    {
        
        private string divisionAbbreviationField;
        
        private string numberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string divisionAbbreviation
        {
            get
            {
                return this.divisionAbbreviationField;
            }
            set
            {
                this.divisionAbbreviationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/vehicle/remote")]
    public partial class VehicleGroupKeyResponse : VehicleGroupKey
    {
        
        private ProtocolEntry[] protocolEntryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("protocolEntry", IsNullable=true, Order=0)]
        public ProtocolEntry[] protocolEntry
        {
            get
            {
                return this.protocolEntryField;
            }
            set
            {
                this.protocolEntryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(VehicleGroupKeyResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/vehicle/remote")]
    public partial class VehicleGroupKey
    {
        
        private string abbreviationField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string abbreviation
        {
            get
            {
                return this.abbreviationField;
            }
            set
            {
                this.abbreviationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/vehicle/remote")]
    public partial class VehicleGroupPart
    {
        
        private VehicleKey vehicleKeyField;
        
        private int positionField;
        
        private string orientationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public VehicleKey vehicleKey
        {
            get
            {
                return this.vehicleKeyField;
            }
            set
            {
                this.vehicleKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int position
        {
            get
            {
                return this.positionField;
            }
            set
            {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string orientation
        {
            get
            {
                return this.orientationField;
            }
            set
            {
                this.orientationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/vehicle/remote")]
    public partial class VehicleGroup
    {
        
        private VehicleGroupKey vehicleGroupKeyField;
        
        private string vehicleGroupTypeField;
        
        private VehicleGroupPart[] vehicleGroupPartField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public VehicleGroupKey vehicleGroupKey
        {
            get
            {
                return this.vehicleGroupKeyField;
            }
            set
            {
                this.vehicleGroupKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string vehicleGroupType
        {
            get
            {
                return this.vehicleGroupTypeField;
            }
            set
            {
                this.vehicleGroupTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("vehicleGroupPart", IsNullable=true, Order=2)]
        public VehicleGroupPart[] vehicleGroupPart
        {
            get
            {
                return this.vehicleGroupPartField;
            }
            set
            {
                this.vehicleGroupPartField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/vehicle/remote")]
    public partial class BrakeSystem
    {
        
        private string brakeTypeField;
        
        private int brakeWeightField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string brakeType
        {
            get
            {
                return this.brakeTypeField;
            }
            set
            {
                this.brakeTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int brakeWeight
        {
            get
            {
                return this.brakeWeightField;
            }
            set
            {
                this.brakeWeightField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/vehicle/remote")]
    public partial class RegistrationDate
    {
        
        private System.DateTime dateField;
        
        private bool dateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        public System.DateTime date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateSpecified
        {
            get
            {
                return this.dateFieldSpecified;
            }
            set
            {
                this.dateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/vehicle/remote")]
    public partial class DueDateAccountComponent
    {
        
        private string dueDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string dueDate
        {
            get
            {
                return this.dueDateField;
            }
            set
            {
                this.dueDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/vehicle/remote")]
    public partial class ServiceIntervalAccountComponent
    {
        
        private string nameField;
        
        private string typeField;
        
        private long valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/vehicle/remote")]
    public partial class ServiceIntervalAccount
    {
        
        private string abbreviationField;
        
        private string datetimeField;
        
        private string effectiveFromField;
        
        private ServiceIntervalAccountComponent serviceIntervalAccountComponentField;
        
        private DueDateAccountComponent dueDateAccountComponentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string abbreviation
        {
            get
            {
                return this.abbreviationField;
            }
            set
            {
                this.abbreviationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string datetime
        {
            get
            {
                return this.datetimeField;
            }
            set
            {
                this.datetimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string effectiveFrom
        {
            get
            {
                return this.effectiveFromField;
            }
            set
            {
                this.effectiveFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public ServiceIntervalAccountComponent serviceIntervalAccountComponent
        {
            get
            {
                return this.serviceIntervalAccountComponentField;
            }
            set
            {
                this.serviceIntervalAccountComponentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public DueDateAccountComponent dueDateAccountComponent
        {
            get
            {
                return this.dueDateAccountComponentField;
            }
            set
            {
                this.dueDateAccountComponentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/vehicle/remote")]
    public partial class DynamicAttribute
    {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/vehicle/remote")]
    public partial class OutOfServiceDate
    {
        
        private System.DateTime dateField;
        
        private bool dateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        public System.DateTime date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateSpecified
        {
            get
            {
                return this.dateFieldSpecified;
            }
            set
            {
                this.dateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(VehicleWithCostCenterRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/mb/intf/vehicle/remote")]
    public partial class Vehicle
    {
        
        private VehicleKey vehicleKeyField;
        
        private string externalNumberField;
        
        private string vehicleTypeAbbreviationField;
        
        private string depotAbbreviationField;
        
        private string descriptionField;
        
        private string registrationNumberField;
        
        private string advertisingField;
        
        private OutOfServiceDate takenOutOfServiceDateField;
        
        private bool countingVehicleField;
        
        private bool countingVehicleFieldSpecified;
        
        private string[] allowedMovingDirectionsField;
        
        private DynamicAttribute[] dynamicAttributesField;
        
        private ServiceIntervalAccount[] serviceIntervalAccountField;
        
        private int lengthField;
        
        private bool lengthFieldSpecified;
        
        private int weightField;
        
        private bool weightFieldSpecified;
        
        private RegistrationDate registrationDateField;
        
        private string[] trainControlSystemsField;
        
        private bool tiltingFunctionField;
        
        private bool tiltingFunctionFieldSpecified;
        
        private int maxSpeedField;
        
        private bool maxSpeedFieldSpecified;
        
        private BrakeSystem[] brakeSystemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public VehicleKey vehicleKey
        {
            get
            {
                return this.vehicleKeyField;
            }
            set
            {
                this.vehicleKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string externalNumber
        {
            get
            {
                return this.externalNumberField;
            }
            set
            {
                this.externalNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string vehicleTypeAbbreviation
        {
            get
            {
                return this.vehicleTypeAbbreviationField;
            }
            set
            {
                this.vehicleTypeAbbreviationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string depotAbbreviation
        {
            get
            {
                return this.depotAbbreviationField;
            }
            set
            {
                this.depotAbbreviationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string registrationNumber
        {
            get
            {
                return this.registrationNumberField;
            }
            set
            {
                this.registrationNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string advertising
        {
            get
            {
                return this.advertisingField;
            }
            set
            {
                this.advertisingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public OutOfServiceDate takenOutOfServiceDate
        {
            get
            {
                return this.takenOutOfServiceDateField;
            }
            set
            {
                this.takenOutOfServiceDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool countingVehicle
        {
            get
            {
                return this.countingVehicleField;
            }
            set
            {
                this.countingVehicleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool countingVehicleSpecified
        {
            get
            {
                return this.countingVehicleFieldSpecified;
            }
            set
            {
                this.countingVehicleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("allowedMovingDirections", IsNullable=true, Order=9)]
        public string[] allowedMovingDirections
        {
            get
            {
                return this.allowedMovingDirectionsField;
            }
            set
            {
                this.allowedMovingDirectionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dynamicAttributes", IsNullable=true, Order=10)]
        public DynamicAttribute[] dynamicAttributes
        {
            get
            {
                return this.dynamicAttributesField;
            }
            set
            {
                this.dynamicAttributesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("serviceIntervalAccount", IsNullable=true, Order=11)]
        public ServiceIntervalAccount[] serviceIntervalAccount
        {
            get
            {
                return this.serviceIntervalAccountField;
            }
            set
            {
                this.serviceIntervalAccountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int length
        {
            get
            {
                return this.lengthField;
            }
            set
            {
                this.lengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lengthSpecified
        {
            get
            {
                return this.lengthFieldSpecified;
            }
            set
            {
                this.lengthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int weight
        {
            get
            {
                return this.weightField;
            }
            set
            {
                this.weightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool weightSpecified
        {
            get
            {
                return this.weightFieldSpecified;
            }
            set
            {
                this.weightFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public RegistrationDate registrationDate
        {
            get
            {
                return this.registrationDateField;
            }
            set
            {
                this.registrationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=15)]
        [System.Xml.Serialization.XmlArrayItemAttribute("trainControlSystem")]
        public string[] trainControlSystems
        {
            get
            {
                return this.trainControlSystemsField;
            }
            set
            {
                this.trainControlSystemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public bool tiltingFunction
        {
            get
            {
                return this.tiltingFunctionField;
            }
            set
            {
                this.tiltingFunctionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tiltingFunctionSpecified
        {
            get
            {
                return this.tiltingFunctionFieldSpecified;
            }
            set
            {
                this.tiltingFunctionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public int maxSpeed
        {
            get
            {
                return this.maxSpeedField;
            }
            set
            {
                this.maxSpeedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxSpeedSpecified
        {
            get
            {
                return this.maxSpeedFieldSpecified;
            }
            set
            {
                this.maxSpeedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=18)]
        [System.Xml.Serialization.XmlArrayItemAttribute("brakeSystem")]
        public BrakeSystem[] brakeSystems
        {
            get
            {
                return this.brakeSystemsField;
            }
            set
            {
                this.brakeSystemsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class importVehicles
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ivu.de/mb/intf/vehicle/remote", Order=0)]
        public IVUServiceIntervals.VehicleRequest vehicleRequest;
        
        public importVehicles()
        {
        }
        
        public importVehicles(IVUServiceIntervals.VehicleRequest vehicleRequest)
        {
            this.vehicleRequest = vehicleRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class importVehiclesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ivu.de/mb/intf/vehicle/remote", Order=0)]
        public IVUServiceIntervals.VehicleResponse vehicleResponse;
        
        public importVehiclesResponse()
        {
        }
        
        public importVehiclesResponse(IVUServiceIntervals.VehicleResponse vehicleResponse)
        {
            this.vehicleResponse = vehicleResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface VehicleWebFacadeChannel : IVUServiceIntervals.VehicleWebFacade, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class VehicleWebFacadeClient : System.ServiceModel.ClientBase<IVUServiceIntervals.VehicleWebFacade>, IVUServiceIntervals.VehicleWebFacade
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public VehicleWebFacadeClient() : 
                base(VehicleWebFacadeClient.GetDefaultBinding(), VehicleWebFacadeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.VehicleWebFacadeBeanPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VehicleWebFacadeClient(EndpointConfiguration endpointConfiguration) : 
                base(VehicleWebFacadeClient.GetBindingForEndpoint(endpointConfiguration), VehicleWebFacadeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VehicleWebFacadeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(VehicleWebFacadeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VehicleWebFacadeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(VehicleWebFacadeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VehicleWebFacadeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IVUServiceIntervals.importVehiclesResponse IVUServiceIntervals.VehicleWebFacade.importVehicles(IVUServiceIntervals.importVehicles request)
        {
            return base.Channel.importVehicles(request);
        }
        
        public IVUServiceIntervals.VehicleResponse importVehicles(IVUServiceIntervals.VehicleRequest vehicleRequest)
        {
            IVUServiceIntervals.importVehicles inValue = new IVUServiceIntervals.importVehicles();
            inValue.vehicleRequest = vehicleRequest;
            IVUServiceIntervals.importVehiclesResponse retVal = ((IVUServiceIntervals.VehicleWebFacade)(this)).importVehicles(inValue);
            return retVal.vehicleResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IVUServiceIntervals.importVehiclesResponse> IVUServiceIntervals.VehicleWebFacade.importVehiclesAsync(IVUServiceIntervals.importVehicles request)
        {
            return base.Channel.importVehiclesAsync(request);
        }
        
        public System.Threading.Tasks.Task<IVUServiceIntervals.importVehiclesResponse> importVehiclesAsync(IVUServiceIntervals.VehicleRequest vehicleRequest)
        {
            IVUServiceIntervals.importVehicles inValue = new IVUServiceIntervals.importVehicles();
            inValue.vehicleRequest = vehicleRequest;
            return ((IVUServiceIntervals.VehicleWebFacade)(this)).importVehiclesAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.VehicleWebFacadeBeanPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.VehicleWebFacadeBeanPort))
            {
                return new System.ServiceModel.EndpointAddress("https://10.8.0.5:20021/intf.vehicle.impl/VehicleWebFacadeBean");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return VehicleWebFacadeClient.GetBindingForEndpoint(EndpointConfiguration.VehicleWebFacadeBeanPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return VehicleWebFacadeClient.GetEndpointAddress(EndpointConfiguration.VehicleWebFacadeBeanPort);
        }
        
        public enum EndpointConfiguration
        {
            
            VehicleWebFacadeBeanPort,
        }
    }
}
