//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZedasVehicleConsist
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://intf.mb.ivu.de/", ConfigurationName="ZedasVehicleConsist.IntfJobsPushPortType")]
    public interface IntfJobsPushPortType
    {
        
        // CODEGEN: Generating message contract since the operation sendIntfJobsExport is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.ivu.de/intf.jobs.impl/IntfJobsPushWebService/IntfJobsSendExport")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void sendIntfJobsExport(ZedasVehicleConsist.sendIntfJobsExport request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.ivu.de/intf.jobs.impl/IntfJobsPushWebService/IntfJobsSendExport")]
        System.Threading.Tasks.Task sendIntfJobsExportAsync(ZedasVehicleConsist.sendIntfJobsExport request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/integration/vehicle/vehiclegroup/standard")]
    public partial class VehicleGroupExport
    {
        
        private VehicleGroup[] vehicleGroupsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("vehicleGroup", IsNullable=false)]
        public VehicleGroup[] vehicleGroups
        {
            get
            {
                return this.vehicleGroupsField;
            }
            set
            {
                this.vehicleGroupsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/integration/vehicle/vehiclegroup/standard")]
    public partial class VehicleGroup
    {
        
        private VehicleGroupKey vehicleGroupKeyField;
        
        private string vehicleGroupTypeField;
        
        private VehicleGroupPart[] vehicleGroupPartField;
        
        private string validFromField;
        
        private bool existsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public VehicleGroupKey vehicleGroupKey
        {
            get
            {
                return this.vehicleGroupKeyField;
            }
            set
            {
                this.vehicleGroupKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string vehicleGroupType
        {
            get
            {
                return this.vehicleGroupTypeField;
            }
            set
            {
                this.vehicleGroupTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("vehicleGroupPart", Order=2)]
        public VehicleGroupPart[] vehicleGroupPart
        {
            get
            {
                return this.vehicleGroupPartField;
            }
            set
            {
                this.vehicleGroupPartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string validFrom
        {
            get
            {
                return this.validFromField;
            }
            set
            {
                this.validFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool exists
        {
            get
            {
                return this.existsField;
            }
            set
            {
                this.existsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/integration/vehicle/vehiclegroup/standard")]
    public partial class VehicleGroupKey
    {
        
        private string abbreviationField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string abbreviation
        {
            get
            {
                return this.abbreviationField;
            }
            set
            {
                this.abbreviationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/integration/vehicle/vehiclegroup/standard")]
    public partial class VehicleKey
    {
        
        private string numberField;
        
        private string externalNumberField;
        
        private string divisionAbbreviationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string externalNumber
        {
            get
            {
                return this.externalNumberField;
            }
            set
            {
                this.externalNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string divisionAbbreviation
        {
            get
            {
                return this.divisionAbbreviationField;
            }
            set
            {
                this.divisionAbbreviationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ivu.de/integration/vehicle/vehiclegroup/standard")]
    public partial class VehicleGroupPart
    {
        
        private VehicleKey vehicleKeyField;
        
        private string positionField;
        
        private string orientationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public VehicleKey vehicleKey
        {
            get
            {
                return this.vehicleKeyField;
            }
            set
            {
                this.vehicleKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=1)]
        public string position
        {
            get
            {
                return this.positionField;
            }
            set
            {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string orientation
        {
            get
            {
                return this.orientationField;
            }
            set
            {
                this.orientationField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendIntfJobsExport
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ivu.de/integration/vehicle/vehiclegroup/standard", Order=0)]
        public ZedasVehicleConsist.VehicleGroupExport vehicleGroupExport;
        
        public sendIntfJobsExport()
        {
        }
        
        public sendIntfJobsExport(ZedasVehicleConsist.VehicleGroupExport vehicleGroupExport)
        {
            this.vehicleGroupExport = vehicleGroupExport;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IntfJobsPushPortTypeChannel : ZedasVehicleConsist.IntfJobsPushPortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class IntfJobsPushPortTypeClient : System.ServiceModel.ClientBase<ZedasVehicleConsist.IntfJobsPushPortType>, ZedasVehicleConsist.IntfJobsPushPortType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public IntfJobsPushPortTypeClient() : 
                base(IntfJobsPushPortTypeClient.GetDefaultBinding(), IntfJobsPushPortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.IntfJobsPushWebServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IntfJobsPushPortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(IntfJobsPushPortTypeClient.GetBindingForEndpoint(endpointConfiguration), IntfJobsPushPortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IntfJobsPushPortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(IntfJobsPushPortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IntfJobsPushPortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(IntfJobsPushPortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IntfJobsPushPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void ZedasVehicleConsist.IntfJobsPushPortType.sendIntfJobsExport(ZedasVehicleConsist.sendIntfJobsExport request)
        {
            base.Channel.sendIntfJobsExport(request);
        }
        
        public void sendIntfJobsExport(ZedasVehicleConsist.VehicleGroupExport vehicleGroupExport)
        {
            ZedasVehicleConsist.sendIntfJobsExport inValue = new ZedasVehicleConsist.sendIntfJobsExport();
            inValue.vehicleGroupExport = vehicleGroupExport;
            ((ZedasVehicleConsist.IntfJobsPushPortType)(this)).sendIntfJobsExport(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task ZedasVehicleConsist.IntfJobsPushPortType.sendIntfJobsExportAsync(ZedasVehicleConsist.sendIntfJobsExport request)
        {
            return base.Channel.sendIntfJobsExportAsync(request);
        }
        
        public System.Threading.Tasks.Task sendIntfJobsExportAsync(ZedasVehicleConsist.VehicleGroupExport vehicleGroupExport)
        {
            ZedasVehicleConsist.sendIntfJobsExport inValue = new ZedasVehicleConsist.sendIntfJobsExport();
            inValue.vehicleGroupExport = vehicleGroupExport;
            return ((ZedasVehicleConsist.IntfJobsPushPortType)(this)).sendIntfJobsExportAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.IntfJobsPushWebServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.IntfJobsPushWebServicePort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8080/intf.jobs.impl/IntfJobsPushWebFacadeBean?wsdl");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return IntfJobsPushPortTypeClient.GetBindingForEndpoint(EndpointConfiguration.IntfJobsPushWebServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return IntfJobsPushPortTypeClient.GetEndpointAddress(EndpointConfiguration.IntfJobsPushWebServicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            IntfJobsPushWebServicePort,
        }
    }
}
