# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  workflow_dispatch:
  #push:
    #branches: [ "main" ]
  #pull_request:
    #branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: "./IVU-Zedas"

    - name: Build
      run:  dotnet build --configuration Release --property:OutputPath=output --property:WarningLevel=0
      working-directory: "./IVU-Zedas"
      
    - name: List files in the repository
      working-directory: IVU-Zedas/IVU-Zedas
      run: |
          dir
          
    - name: List files in the repository
      working-directory: IVU-Zedas
      run: |
          dir
          
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
       name: BuildFunction
       path: "./IVU-Zedas/output"


